services:
  redis:
    image: redis
    container_name: redis
    ports:
      - "6379:6379"
    restart: unless-stopped

  postgres:
    image: postgres:17
    container_name: postgres
    shm_size: 128mb
    ports:
      - "5432:5432"
    env_file:
      - ../.env
    restart: unless-stopped

  magplex:
    container_name: magplex
    ports:
      - "8080:8080"    # Web UI
      - "34400:34400"  # STB
    build:
      context: ..
    env_file:
      - ../.env
    depends_on:
      - redis
      - postgres
    restart: unless-stopped