services:
  nginx:
    image: nginx:latest
    container_name: nginx_proxy
    ports:
      - "8080:8080"
      - "34400:34400"
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf:ro
    depends_on:
      - magplex
    restart: unless-stopped

  redis:
    image: redis
    container_name: redis
    ports:
      - "6379:6379"
    restart: unless-stopped

  magplex:
    container_name: magplex
    build:
      context: ..
    env_file:
      - ../.env
    depends_on:
      - redis
    restart: unless-stopped